# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import customer_pb2 as customer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in customer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSeller = channel.unary_unary(
                '/customer.CustomerDB/CreateSeller',
                request_serializer=customer__pb2.CreateSellerRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.LoginSeller = channel.unary_unary(
                '/customer.CustomerDB/LoginSeller',
                request_serializer=customer__pb2.LoginRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.LogoutSeller = channel.unary_unary(
                '/customer.CustomerDB/LogoutSeller',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.ValidateSessionSeller = channel.unary_unary(
                '/customer.CustomerDB/ValidateSessionSeller',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.CreateBuyer = channel.unary_unary(
                '/customer.CustomerDB/CreateBuyer',
                request_serializer=customer__pb2.CreateBuyerRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.LoginBuyer = channel.unary_unary(
                '/customer.CustomerDB/LoginBuyer',
                request_serializer=customer__pb2.LoginRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.LogoutBuyer = channel.unary_unary(
                '/customer.CustomerDB/LogoutBuyer',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.ValidateSessionBuyer = channel.unary_unary(
                '/customer.CustomerDB/ValidateSessionBuyer',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.GetSellerRating = channel.unary_unary(
                '/customer.CustomerDB/GetSellerRating',
                request_serializer=customer__pb2.SellerRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.ProvideFeedback = channel.unary_unary(
                '/customer.CustomerDB/ProvideFeedback',
                request_serializer=customer__pb2.FeedbackRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.GetBuyerPurchases = channel.unary_unary(
                '/customer.CustomerDB/GetBuyerPurchases',
                request_serializer=customer__pb2.BuyerRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.AddPurchase = channel.unary_unary(
                '/customer.CustomerDB/AddPurchase',
                request_serializer=customer__pb2.AddPurchaseRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/customer.CustomerDB/GetCart',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.AddToCart = channel.unary_unary(
                '/customer.CustomerDB/AddToCart',
                request_serializer=customer__pb2.CartRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.RemoveFromCart = channel.unary_unary(
                '/customer.CustomerDB/RemoveFromCart',
                request_serializer=customer__pb2.CartRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/customer.CustomerDB/SaveCart',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/customer.CustomerDB/ClearCart',
                request_serializer=customer__pb2.SessionRequest.SerializeToString,
                response_deserializer=customer__pb2.DBResponse.FromString,
                _registered_method=True)


class CustomerDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSessionSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSessionBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSeller,
                    request_deserializer=customer__pb2.CreateSellerRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'LoginSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginSeller,
                    request_deserializer=customer__pb2.LoginRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'LogoutSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutSeller,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'ValidateSessionSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSessionSeller,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'CreateBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBuyer,
                    request_deserializer=customer__pb2.CreateBuyerRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'LoginBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginBuyer,
                    request_deserializer=customer__pb2.LoginRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'LogoutBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutBuyer,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'ValidateSessionBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSessionBuyer,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=customer__pb2.SellerRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'ProvideFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideFeedback,
                    request_deserializer=customer__pb2.FeedbackRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'GetBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchases,
                    request_deserializer=customer__pb2.BuyerRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'AddPurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPurchase,
                    request_deserializer=customer__pb2.AddPurchaseRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'AddToCart': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToCart,
                    request_deserializer=customer__pb2.CartRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'RemoveFromCart': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromCart,
                    request_deserializer=customer__pb2.CartRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=customer__pb2.SessionRequest.FromString,
                    response_serializer=customer__pb2.DBResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'customer.CustomerDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('customer.CustomerDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/CreateSeller',
            customer__pb2.CreateSellerRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/LoginSeller',
            customer__pb2.LoginRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogoutSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/LogoutSeller',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSessionSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/ValidateSessionSeller',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/CreateBuyer',
            customer__pb2.CreateBuyerRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/LoginBuyer',
            customer__pb2.LoginRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogoutBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/LogoutBuyer',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSessionBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/ValidateSessionBuyer',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/GetSellerRating',
            customer__pb2.SellerRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/ProvideFeedback',
            customer__pb2.FeedbackRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/GetBuyerPurchases',
            customer__pb2.BuyerRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/AddPurchase',
            customer__pb2.AddPurchaseRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/GetCart',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/AddToCart',
            customer__pb2.CartRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/RemoveFromCart',
            customer__pb2.CartRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/SaveCart',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/customer.CustomerDB/ClearCart',
            customer__pb2.SessionRequest.SerializeToString,
            customer__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
