# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import product_pb2 as product__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductDBStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterItem = channel.unary_unary(
                '/product.ProductDB/RegisterItem',
                request_serializer=product__pb2.RegisterItemRequest.SerializeToString,
                response_deserializer=product__pb2.DBResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/product.ProductDB/GetItem',
                request_serializer=product__pb2.ItemRequest.SerializeToString,
                response_deserializer=product__pb2.DBResponse.FromString,
                _registered_method=True)
        self.UpdateItemPrice = channel.unary_unary(
                '/product.ProductDB/UpdateItemPrice',
                request_serializer=product__pb2.UpdatePriceRequest.SerializeToString,
                response_deserializer=product__pb2.DBResponse.FromString,
                _registered_method=True)
        self.UpdateItemQuantity = channel.unary_unary(
                '/product.ProductDB/UpdateItemQuantity',
                request_serializer=product__pb2.UpdateQuantityRequest.SerializeToString,
                response_deserializer=product__pb2.DBResponse.FromString,
                _registered_method=True)
        self.GetSellerItems = channel.unary_unary(
                '/product.ProductDB/GetSellerItems',
                request_serializer=product__pb2.SellerRequest.SerializeToString,
                response_deserializer=product__pb2.DBResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/product.ProductDB/SearchItems',
                request_serializer=product__pb2.SearchRequest.SerializeToString,
                response_deserializer=product__pb2.DBResponse.FromString,
                _registered_method=True)
        self.MakePurchase = channel.unary_unary(
                '/product.ProductDB/MakePurchase',
                request_serializer=product__pb2.PurchaseRequest.SerializeToString,
                response_deserializer=product__pb2.DBResponse.FromString,
                _registered_method=True)
        self.ProvideItemFeedback = channel.unary_unary(
                '/product.ProductDB/ProvideItemFeedback',
                request_serializer=product__pb2.ItemFeedbackRequest.SerializeToString,
                response_deserializer=product__pb2.DBResponse.FromString,
                _registered_method=True)


class ProductDBServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItemQuantity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakePurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideItemFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterItem,
                    request_deserializer=product__pb2.RegisterItemRequest.FromString,
                    response_serializer=product__pb2.DBResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=product__pb2.ItemRequest.FromString,
                    response_serializer=product__pb2.DBResponse.SerializeToString,
            ),
            'UpdateItemPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemPrice,
                    request_deserializer=product__pb2.UpdatePriceRequest.FromString,
                    response_serializer=product__pb2.DBResponse.SerializeToString,
            ),
            'UpdateItemQuantity': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItemQuantity,
                    request_deserializer=product__pb2.UpdateQuantityRequest.FromString,
                    response_serializer=product__pb2.DBResponse.SerializeToString,
            ),
            'GetSellerItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerItems,
                    request_deserializer=product__pb2.SellerRequest.FromString,
                    response_serializer=product__pb2.DBResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=product__pb2.SearchRequest.FromString,
                    response_serializer=product__pb2.DBResponse.SerializeToString,
            ),
            'MakePurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.MakePurchase,
                    request_deserializer=product__pb2.PurchaseRequest.FromString,
                    response_serializer=product__pb2.DBResponse.SerializeToString,
            ),
            'ProvideItemFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideItemFeedback,
                    request_deserializer=product__pb2.ItemFeedbackRequest.FromString,
                    response_serializer=product__pb2.DBResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.ProductDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.ProductDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductDB(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductDB/RegisterItem',
            product__pb2.RegisterItemRequest.SerializeToString,
            product__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductDB/GetItem',
            product__pb2.ItemRequest.SerializeToString,
            product__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItemPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductDB/UpdateItemPrice',
            product__pb2.UpdatePriceRequest.SerializeToString,
            product__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateItemQuantity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductDB/UpdateItemQuantity',
            product__pb2.UpdateQuantityRequest.SerializeToString,
            product__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductDB/GetSellerItems',
            product__pb2.SellerRequest.SerializeToString,
            product__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductDB/SearchItems',
            product__pb2.SearchRequest.SerializeToString,
            product__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakePurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductDB/MakePurchase',
            product__pb2.PurchaseRequest.SerializeToString,
            product__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideItemFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.ProductDB/ProvideItemFeedback',
            product__pb2.ItemFeedbackRequest.SerializeToString,
            product__pb2.DBResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
